name: Blip
options:
  bundleIdPrefix: io.liess.blip
  deploymentTarget:
    iOS: "26.0"
    macOS: "26.0"
  createIntermediateGroups: true
  defaultConfig: Debug
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "6.2"
    SWIFT_DEFAULT_ACTOR_ISOLATION: MainActor
    SWIFT_APPROACHABLE_CONCURRENCY: "YES"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
  configs:
    Debug:
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG"
    Release:
      SWIFT_OPTIMIZATION_LEVEL: "-O"
      SWIFT_COMPILATION_MODE: "wholemodule"

configs:
  Debug: debug
  Release: release

targets:
  # --- macOS App ---
  Blip:
    type: application
    platform: macOS
    sources:
      - path: Blip
        createIntermediateGroups: true
    settings:
      base:
        INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "Blip uses your location to show nearby aircraft and ships."
        PRODUCT_BUNDLE_IDENTIFIER: "io.liess.blip"
        PRODUCT_NAME: "Blip"
        GENERATE_INFOPLIST_FILE: "YES"
        ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
        MACOSX_DEPLOYMENT_TARGET: "26.0"
        DEVELOPMENT_TEAM: "Y7B687M9H5"
        CODE_SIGN_STYLE: "Automatic"
    dependencies: []

  # --- iOS App ---
  Blip-iOS:
    type: application
    platform: iOS
    sources:
      - path: Blip
        createIntermediateGroups: true
    settings:
      base:
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: "YES"
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: "YES"
        INFOPLIST_KEY_UILaunchScreen_Generation: "YES"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "Blip uses your location to show nearby aircraft and ships."
        PRODUCT_BUNDLE_IDENTIFIER: "io.liess.blip"
        PRODUCT_NAME: "Blip"
        GENERATE_INFOPLIST_FILE: "YES"
        ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
        IPHONEOS_DEPLOYMENT_TARGET: "26.0"
        DEVELOPMENT_TEAM: "Y7B687M9H5"
        CODE_SIGN_STYLE: "Automatic"
    dependencies: []

  # --- Unit Tests (macOS) ---
  BlipTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: BlipTests
        createIntermediateGroups: true
    dependencies:
      - target: Blip
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "io.liess.blip.tests"
        GENERATE_INFOPLIST_FILE: "YES"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Blip.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Blip"
        BUNDLE_LOADER: "$(TEST_HOST)"

  # --- UI Tests (macOS) ---
  BlipUITests:
    type: bundle.ui-testing
    platform: macOS
    sources:
      - path: BlipUITests
        createIntermediateGroups: true
    dependencies:
      - target: Blip
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "io.liess.blip.uitests"
        GENERATE_INFOPLIST_FILE: "YES"
        TEST_TARGET_NAME: "Blip"

schemes:
  # macOS scheme (build + test)
  Blip:
    build:
      targets:
        Blip: all
        BlipTests: [test]
        BlipUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - BlipTests
        - BlipUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  # iOS scheme (build + run on device/simulator)
  Blip-iOS:
    build:
      targets:
        Blip-iOS: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
